import React from "react";
import "../Content.css";

export default function Updates() {
  return (
    <div className="content-container2">
      <div className="content-Title">Updates from OpenFWI</div>
      <div className="content-text">
        June 22, 2023: Kimberlina 3D-V1 is released
        <ul>
          <li>
            Kimberlina 3D-V1 data is released at{" "}
            <a
              href="https://www.edx.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              EDX website
            </a>
            .
          </li>
          <li>
            The details can be found available on{" "}
            <a
              href="https://rmets.onlinelibrary.wiley.com/doi/full/10.1002/gdj3.191"
              target="_blank"
              rel="noopener noreferrer"
            >
              Geophysical Data Journal paper
            </a>
            .
          </li>
        </ul>
        <br />
        Nov 16, 2022: Benchmark Update.
        <ul>
          <li>
            Some errors in the benchmarks are fixed. The benchmarks are
            consistent with the results generated by the released pre-trained
            models now.
          </li>
        </ul>
        <br />
        Nov. 3, 2022: OpenFWI tutorial is released on colab.
        <ul>
          <li>
            We create a hands-on tutorial for demonstration with toy dataset,
            available on{" "}
            <a
              href="https://colab.research.google.com/drive/17s5JmVs9ABl8MpmFlhWMSslj9_d5Atfx"
              target="_blank"
              rel="noopener noreferrer"
            >
              google colab
            </a>
            .
          </li>
        </ul>
        <br />
        Sep 17, 2022: OpenFWI is accepted by NeurIPS 2022.
        <ul>
          <li>
            The paper{" "}
            <a
              href="https://openreview.net/forum?id=7w-a8PYPlP&referrer=%5BAuthor%20Console%5D(%2Fgroup%3Fid%3DNeurIPS.cc%2F2022%2FTrack%2FDatasets_and_Benchmarks%2FAuthors%23your-submissions)"
              target="_blank"
              rel="noopener noreferrer"
            >
              OpenFWI: Large-scale Multi-structural Benchmark Datasets for Full
              Waveform Inversion
            </a>{" "}
            will be presented as a spotlight in NeurIPS 2022 Dataset and
            Benchmark track.
          </li>
        </ul>
        <br />
        Aug 17, 2022: OpenFWI tutorial is released.
        <ul>
          <li>
            We will update the tutorial as OpenFWI evolves and improve based on
            the feedback from the community.
          </li>
        </ul>
        <br />
        Aug 15, 2022: OpenFWI codes and pretrained models are released.
        <ul>
          <li>
            Codes for InversionNet and VelocityGAN available on{" "}
            <a
              href="https://github.com/lanl/OpenFWI"
              target="_blank"
              rel="noopener noreferrer"
            >
              Github
            </a>
            .
          </li>
        </ul>
        <br />
        June 17, 2022: OpenFWI arxiv version published.
        <ul>
          <li>
            OpenFWI paper available at{" "}
            <a
              href="https://arxiv.org/abs/2111.02926"
              target="_blank"
              rel="noopener noreferrer"
            >
              arXiv
            </a>
            .
          </li>
        </ul>
        <br />
        June 13, 2022: First official release of OpenFWI.
        <ul>
          <li>
            Eleven 2D datasets are available for download! Benchmark performance
            have been released!
          </li>
        </ul>
      </div>
    </div>
  );
}
